// <auto-generated />
using System;
using Menu_Restaurante_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Menu_Restaurante_API.Migrations
{
    [DbContext(typeof(MenuRestauranteContext))]
    [Migration("20251130222731_favorite")]
    partial class favorite
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.12");

            modelBuilder.Entity("Menu_Restaurante_API.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "",
                            IsActive = true,
                            Name = "Bebidas",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "",
                            IsActive = true,
                            Name = "Postres",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "",
                            IsActive = true,
                            Name = "Platos Principales",
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            Description = "",
                            IsActive = true,
                            Name = "Pizzas",
                            UserId = 2
                        },
                        new
                        {
                            Id = 5,
                            Description = "",
                            IsActive = true,
                            Name = "Empanadas",
                            UserId = 2
                        },
                        new
                        {
                            Id = 6,
                            Description = "",
                            IsActive = true,
                            Name = "Bebidas",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("Menu_Restaurante_API.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DiscountPercent")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HappyHourEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan?>("HappyHourEnd")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("HappyHourStart")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 3,
                            Description = "Clásica milanesa con papas fritas doradas",
                            DiscountPercent = 0,
                            HappyHourEnabled = false,
                            IsFavorite = false,
                            Name = "Milanesa con papas fritas",
                            Price = 2500m,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "Helado artesanal de chocolate amargo",
                            DiscountPercent = 10,
                            HappyHourEnabled = true,
                            IsFavorite = false,
                            Name = "Helado de chocolate",
                            Price = 900m,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "IPA rubia elaborada localmente",
                            DiscountPercent = 20,
                            HappyHourEnabled = true,
                            IsFavorite = false,
                            Name = "Cerveza artesanal 500ml",
                            Price = 1200m,
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            Description = "Mozzarella, tomate y albahaca fresca",
                            DiscountPercent = 0,
                            HappyHourEnabled = false,
                            IsFavorite = false,
                            Name = "Pizza Margarita",
                            Price = 1800m,
                            UserId = 2
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 5,
                            Description = "Empanada jugosa con carne cortada a cuchillo",
                            DiscountPercent = 0,
                            HappyHourEnabled = false,
                            IsFavorite = false,
                            Name = "Empanada de Carne",
                            Price = 350m,
                            UserId = 2
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 6,
                            Description = "Botella de Coca-Cola 1.5 litros",
                            DiscountPercent = 30,
                            HappyHourEnabled = true,
                            IsFavorite = false,
                            Name = "Gaseosa Cola 1.5L",
                            Price = 800m,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("Menu_Restaurante_API.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RestaurantName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Visits")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "",
                            Email = "sanmartin@gmail.com",
                            Password = "12345",
                            Phone = "",
                            RestaurantName = "",
                            Username = "Restaurante San Martín",
                            Visits = 0
                        },
                        new
                        {
                            Id = 2,
                            Address = "",
                            Email = "pizzeria@gmail.com",
                            Password = "abcd1234",
                            Phone = "",
                            RestaurantName = "",
                            Username = "Pizzería El Rincón",
                            Visits = 0
                        });
                });

            modelBuilder.Entity("Menu_Restaurante_API.Entities.Category", b =>
                {
                    b.HasOne("Menu_Restaurante_API.Entities.User", "User")
                        .WithMany("Categories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Menu_Restaurante_API.Entities.Product", b =>
                {
                    b.HasOne("Menu_Restaurante_API.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Menu_Restaurante_API.Entities.User", "User")
                        .WithMany("Products")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Menu_Restaurante_API.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Menu_Restaurante_API.Entities.User", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
